### PR TITLE
Python

### PR DESCRIPTION
**Pull request by hannorein**
This updates the python interface to reflect the changes in the c version.

I've added a few unit tests. Have a look at them to check out the new syntax: https://github.com/hannorein/assist/blob/python/assist/test/test_basic.py I think it looks nice and clean.

There is still a lot of cleanup to do. We need better error handling for all kind of things that can go wrong. And maybe most importantly, we need a way to interpolate between timesteps. I have an idea on how to do that nicely, but I still need to implement it...

### CODE REVIEW

**Comment by matthewholman** [comment]
That looks great!  As you said, nice and clean.

For the interpolation, are you thinking of storing the coefficients from IAS15?  It would be nice to be able to retain and re-interpolate the full trajectory.

**Comment by hannorein** [comment]
Exactly. I was thinking that we could just use the Simulation Archive for that. The archive can be stored both in memory or in a file. So it's very flexible. 

On thing I'm not sure about. Do you think we need a way to efficiently interpolate an integration while it's running? For example to produce outputs at a predetermined interval that is smaller than the timestep? Because if we don't need to store all the coefficients and simply do the interpolation while the simulation is running, it would be faster.

**Comment by matthewholman** [comment]
If one wanted to match astrometric or radar observations, with light time corrections, that could be done as an integration proceeds.  However, it may be cleaner and almost as efficient to keep those two steps (integrating the trajectory and matching the observations) separate.

I don't have a strong opinion.

**Comment by hannorein** [comment]
Thanks. That's helpful. Then I'll try out the storing part first. And if efficiency ever becomes an issue, we can do work on it...

**Comment by hannorein** [comment]
I'm trying to do the interpolation stuff but I'm not getting the right results. IAS15 uses Horner's method internally but the `assist_interpolate` function does not.  Do you remember the origin of the current `assist_interpolate` function? Was there a reason to write it this way?

**Comment by hannorein** [comment]
Playing around a bit more. I don't think the `assist_interpolate` function is doing the interpolation correctly. But I suspect you would have noticed that... I'm probably missing something.

**Comment by matthewholman** [comment]
Actually, most of that code is borrowed from a part of the IAS15 code.  I believe it's the part that is evaluating the polynomials at the end of the integration interval.

**Comment by hannorein** [comment]
Thanks. I'll take it back. I think it's correct - the error must be elsewhere.

**Comment by hannorein** [comment]
I've implemented a way to use the SimulationArchived framework for the interpolation. It's a bit of a hack right now and not very efficient, but I think it's promising. Here's how the syntax looks like (only in C for now, but it's easy to port): 

https://github.com/hannorein/assist/blob/python/unit_tests/interpolation/problem.c

If we do go down this route, then we could get rid of a lot of overhead:
- `assist_integrate()`
- `heartbeat` function
- `pre_timestep_modifications`
- `last_state_..`, `output_t`, `output_state`, `nsubsteps`, hg`, variables

(The unit test using the `assist_integrate` function fails right now because I had to comment out the `reb_update_acceleration()` call in `pre_timestep_modifications`. )

**Comment by matthewholman** [comment]
This does look very promising.  You mentioned that these same steps could be done in memory.  Is that still the case?  (Speed will be moderately important for orbit fitting.)

**Comment by hannorein** [comment]
It needs a bit more work on the REBOUND side, but basically, yes. Internally the SimulationArchive stuff is already written to a memory buffer first, and only outputted to a file at the end. However, it will never be as fast as just calculating all the outputs on the fly. I think for the orbit fitting where speed matters, we would want something basic. I've tried and failed before, but I'll try to code something up once more...

**Comment by hannorein** [comment]
Alright, have a look at this: https://github.com/hannorein/assist/blob/python/unit_tests/onthefly_interpolation/problem.c

This unit test integrates two simulations with the same initial conditions in different ways.
1) Using the normal `reb_integrate()` function and `exact_finish_time=1`. This always gets you directly to the requested output time but might use very small timesteps if the outputs are closely spaced.
2) Using a new `assist_integrate_or_interpolate()` function that looks very similar to `reb_integrate()` but does a an interpolation instead of an integration if possible. The adaptive timesteps are as large as they can be and don't get reduced to match a requested output time.

I like how this looks and it's about as fast as it can get. It doesn't store the coefficients though, so not ideal for the light travel time iteration.

**Comment by hannorein** [comment]
Cool. I'll polish things up a bit then. I think we have very useable and flexible user interface now. We can always improve it later. 

For the light travel time application, I wouldn't be surprised if just redoing the integration at each iteration is almost as fast/faster in the end. The timesteps are typically large (40 days) and I suspect observations will not span that many years. Also, in addition to the cache of the ephemeris data, we could implement a cache for the ephemeris polynomials coefficients themselves. But everything depends on the number of observations, how closely they are spaced, length of integration, how many iterations are needed, etc.

**Comment by matthewholman** [comment]
All very good points.  I definitely agree that we have a very flexible and useable interface now.  It's going to be a lot of fun to put this to good use!

**Comment by matthewholman** [comment]
Here's another thought related to caches and orbit fitting.  Since the fitting process normally tests sets of initial conditions that are relatively nearby, we could cache the IAS15 polynomial coefficients for the various integration segments as starting guesses for the integration of other nearby initial conditions.  It may not be worth the trouble, because it wouldn't be very general.  But it might reduce the number of predictor-corrector iterations.

**Comment by hannorein** [comment]
Good points. I agree with everything. I also suspect it might not be worth it given IAS15 only uses 2-3 iterations anyway.

**Comment by hannorein** [comment]
I still need to update the python notebooks, but as long as you're happy with it, I think this can be merged. I'd rather send you a few smaller pull request than pile everything into one gigantic one.

(I've also added the apophis unit test to this PR which closes #46, see https://github.com/hannorein/assist/blob/python/unit_tests/apophis/problem.c)

**Comment by matthewholman** [comment]
This is awesome!

**Pull request merged**
