### PR TITLE
mkdocs

### PR DESCRIPTION
**Pull request by hannorein**
@matthewholman and @aryaakmal, have a look and let me know your thoughts on #68. Here's a demo: https://assist-demo.readthedocs.io/en/latest/

- The main difference is that the source of the documentation is just markdown which I find easier to read and work with.
- The documentation now includes all the c and python examples, including the images from the notebooks. Everything is automatically generated. If we want to include a new example, we only need to edit the [mkdocs.yml](https://github.com/hannorein/assist/blob/mkdocs/mkdocs.yml) file.
- The installation page for c and python is the same, you can select either c or python in the little tabs on the page to see the different syntax (I think that neat). 
- I'd like to add one or two extra pages which describe the various settings (how to forces turned on and off, etc)

### CODE REVIEW

**Comment by aryaakmal** [comment]
I look forward to seeing what this looks like on readthedocs. One thing
about the sphinx version that I did like was that it was easy to add links
to the index by simply adding to the body of the index file - and sphinx
incorporated them in the right panel automatically. It isn't completely
clear to me looking at the files how that would work here ... I have zero
familiarity with javascript. But I assume it will be straightforward to
figure it out once there is a template to follow.

**Comment by hannorein** [comment]
I don't think I understand. There is no javascript involved. This is probably not what you're asking but to add an item to the table of contents you simple add a file to the `docs/` directory and add one line with the new file's name to `mkdocs.yml`.

**Comment by aryaakmal** [comment]
I'll just wait and see - I  am sure it will be ok. But I do not see the
mkdocs.yml file. I do see some new directories under your docs/ directory,
including a javascripts/ directory containing a number of .js files ...

**Comment by hannorein** [comment]
The yml file is linked in the first comment on this PR (see above). I'm not sure why you're not seeing the file. The javascript is only for rendering LaTeX equations - but it's just for rendering - no need to ever touch the javascript part

**Comment by aryaakmal** [comment]
Yup, got it.

**Comment by matthewholman** [comment]
@hannorein, @aryaakmal, the documentation is looking really good!

**Pull request merged**
