### PR TITLE
Added new example that is shorter, self-contained, and has more documentation

### PR DESCRIPTION
**Pull request by hannorein**
I had a bit of trouble working my way through the example. So here is an example that is even "simpler" than the "simplest" previous example.

One thing I couldn't quite figure out is the meaning of the `jd_ref` variable. Is this the reference time for the ephemeris data files? But it looks like that is actually in the data files themselves? So is this just for internal use? In what circumstance would I change it?

### CODE REVIEW

**Comment by matthewholman** [comment]
jd_ref is the julian date zero point.  Earlier we were using the full julian date (TBD) as the internal time scale, but doing so limits the time resolution because several of the leading digits don't change in typical integrations.  Now the julian date is given by
jd = jd_ref + t,
where all are in days (TDB).  The default for jd_ref is  2451545.0, J2000.0.  The only reason to change this, to say the present, would be if you need every last bit of time resolution.   That is probably extremely rare.  And the precision of observations or ephemeris may not merit it.  I agree with your suggestion of setting this internally.

**Comment by hannorein** [comment]
Thanks! That makes sense.

Just one quick follow up question: The `integration_function` takes `tstart` and `tend` as full Julian dates. Wouldn't it make sense/give you more precision if those times were relative to `jd_ref`?

**Comment by matthewholman** [comment]
Yes, you are right.  I'm not sure what is best from a UX point of view, to have the user externally use a full julian date (which is probably easier) or to give the user access to the full precision.  I figured the user would end up calculating t = jd-jd_ref.  Normally the user has round number for an initial time, so it's ok.  What are your thoughts?

**Comment by hannorein** [comment]
I think both of these options are consistent:

1) Keep the `jd_ref` exposed as it is, just interpret the user provided `tstart` and `tend` as times relative to `jd_ref`.
2) Keep `tstart` and `tend` as full Julian days. Hide `jd_ref` from the user. 

I think I like 1) better. As you mention, it is fairly common to use a reference Julian date. And after all, this is a specialized library written specifically to get the most accurate result possible.

**Comment by hannorein** [comment]
One more thing: If you want to go with 1) then I would also make the output times relative to `jd_ref` to be consistent.

**Comment by matthewholman** [comment]
Another good suggestion.  Let's go with the first option but also make the the output times relative to jd_ref, as you say.

**Comment by matthewholman** [comment]
I *believe* this is all set.  tstart, tend, and the output were already relative to jd_ref.  I forgot that that was already the case.

**Comment by matthewholman** [comment]
Regarding example code, I have a number of jupyter notebooks with examples.  Do you have a suggestion for organizing those?  Put them all in one directory or have separate directories that parallel the ones with c code?

**Pull request merged**
