### PR TITLE
Updated 3666 Holman example

### PR DESCRIPTION
**Pull request by hannorein**
Have a look if you like these changes. I think it makes sense to have one example notebook focus on one topic. This notebook lends itself to explain variational equations. I've left all of the text describing variational equations mostly unchanged. I've removed the parts about the timestep. I'm also not comparing the outputs to the data in `holman_sb.txt`.  Again, trying to keep it to one topic. 

We still need to update 5303_Ceres.ipynb and 841000_Farnocchia.ipynb. 

Shall we have a separate set of notebooks which are reproducing all the figures of the paper? I would keep them very simple without a lot of comments.

### CODE REVIEW

**Comment by aryaakmal** [comment]
@hannorein - I am in favor of small notebook examples that focus
minimally on specific  topics as opposed to large examples that do multiple
topics.

**Comment by hannorein** [comment]
One more thing. The original notebook had several copies of the perturbed asteroid in the simulation. I think they were all identical. I've removed the copies. So now there is one asteroid, one perturbed asteroid, and one variational equation.

**Comment by matthewholman** [comment]
I am also in favor of small, focused notebooks.

I think the original notebook had seven real particles, the central trajectory and a perturbed trajectory for each component.  That's more than is needed for demonstration purposes.

The (84100) Farnocchia notebook wouldn't be fundamentally different from the (3666) Holman notebook, just different initial conditions, but the 5303_Ceres notebook has different figures.

**Comment by hannorein** [comment]
Ok. Thanks. Hm. That's what I thought but I'm not sure if they had been setup correctly then (they might have been all identical), but it doesn't matter.

One more thing again. There was a speed comparison in the notebook:

    (3666) Holman with ASSIST
         10 d:      0.0307 s
        100 d:      0.0458 s
       1000 d:      0.273  s
      10000 d:      2.53   s
     100000 d:     29.2    s
    1000000 d:     288     s
    
    (3666) Holman with small body code
         10 d:      0.020
        100 d:      0.013
       1000 d:      0.024
      10000 d:      0.059
     100000 d:      0.403
    1000000 d:      3.811

I would love to see how the speed compares now. But to make it fair, we'd need to know what was integrated with the small body code? Only the asteroid or also some perturbed or variational particles?

**Comment by matthewholman** [comment]
I added six rows with of the same particle to a 6x6 identity matrix times a scale factor (1e-8).  Maybe the addition line got deleted.

**Comment by matthewholman** [comment]
The times for the small bodies code are for just a single trajectory with no variational particles.  I can ask Davide for corresponding numbers when variational particles are included.

**Comment by hannorein** [comment]
I'm sorry, you're right about the setup and the identity matrix! 

Integrating 1 million days takes me 3.47s compared to 3.811s with the small body code. 

Of course, it's unfair unless we have exactly the same number of outputs, run it on the same machine, etc. But it looks like we're definitely competitive!

I get the runtime down to 1.9 s if I set `eih_loop_limit=1` to only include GR from the Sun. The default right now is to include GR for all planets. I'm not sure what should be the default (I think you mentioned that this should be a free parameter for the user to choose).

**Comment by matthewholman** [comment]
Wow, that's really cool!  Very, very satisfying.  I have updated the manuscript, but I will also double check the speed on my laptop.

Regarding the GR model, I think either setting eih_loop_limit=1 with eih_GR or using simple_GR makes sense as a default.  My understanding is that only in rare cases is GR with a full double loop over the masses needed or used by JPL.

**Comment by aryaakmal** [comment]
Very cool, indeed.

**Pull request merged**
