### PR TITLE
Large asteroid file

### PR DESCRIPTION
**Pull request by hannorein**
This is work in progress with the goal of ASSIST reading the large asteroid file. 

So far I've cleanup up the jpl routines (more comments, no more goto statements). Next up, cleanup up the spk routines.

### CODE REVIEW

**Comment by matthewholman** [comment]
This is looking great, Hanno!

**Comment by hannorein** [comment]
One thing that this will break is the ordering of the asteroids in the direct force evaluation. I don't think this should matter -- all the contributions are very small. But it might change the precise floating point number we get.

**Comment by hannorein** [comment]
Alright. This was a bit more involved than I hoped, but I think this should be working. I basically had to rewrite the entire routines for both planets and asteroid files. On the positive side, it should be much easier to maintain in the future. 

Still to do:
- [ ]  I'm not sure how to test this. I've been rerunning the existing units tests with the extended asteroids file. We get slightly different results (and because the units tests requirements are very tight, they will fail). I guess that is expected. But do you have any ideas on how to run a proper test? 
- [ ]  I'm not finding the right masses for the TNOs yet. ASSIST will output a warning and treat the masses as 0 for now.
- [ ]  We should also use the ephemeris file for the other constants that are hard coded right now. 
- [ ]  Documentation needs to be updated.

**Comment by matthewholman** [comment]
Thank you so much for all this work, @hannorein !

Regarding how to test this and to develop another set of unit tests, I will contact Davide about repeating the term-by-term comparison, as well as some integration tests, this time with the large asteroid file.  I don't anticipate finding any differences, but it will be reassuring.   Once those are verified, I/we can do some runs, record the results, and make another, parallel set of unit tests.  Since each of the unit tests has to initialize the ephemeris, we can easily have a parallel set of tests that use the larger asteroid file.

I agree regarding the other hard-coded constants.  Ideally those will all come from the ephemeris files.  That will make adjusting to future versions of DE4xx easy.

Perhaps @aryaakmal can work on adding to the documentation.

**Comment by hannorein** [comment]
I've implemented all the rest. I am using a lookup table which I found in a README file (https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/README.txt) to match the SPK_ID to the ID in the DE440/441 files. I don't like it - we could just as well hard code the masses themselves - but I don't see another way to do this mapping.

All other constants (J2, AU, RE, etc) are now also read from the ephemeris files. I've deleted the const.h file.

The one thing we still need to add is tests. But I think this is ready to be merged. All the tests using the n16 file are still passing.

**Comment by matthewholman** [comment]
Yeah, it's unfortunate that identifiers in the asteroid binary files are not cleaner.  Maybe they will be in future versions.

Regardless, thanks again for all this!   I'll get numbers for updating the unit tests.

**Pull request merged**
