### PR TITLE
Gr speed test

### PR DESCRIPTION
**Pull request by matthewholman**
I made a version of the eih_GR function that separates the calculations for the real particles from those for the variational particles.  This entails a little duplicate calculation when there are variational particles, but it does no extra work if there are no variational particles.

### CODE REVIEW

**Comment by hannorein** [comment]
Nice! That's not bad. I think you can get a few more percent if you precalculate the inverse of C2.

**Comment by matthewholman** [comment]
I'm not sure what's causing the tests to fail.

**Comment by hannorein** [comment]
It's your debugging file. Comment out the flush/close commands

**Comment by hannorein** [comment]
On my end, your changes add up to a 50% improvement! I've tried out a few more things, but couldn't find anything that is (measurably) faster than what you did. 

All together, compared to before the cache and these optimizations were implemented, we've managed to speed things up by a factor of ~ 7.6x - 8.7x (depending on the machine).

**Comment by aryaakmal** [comment]
Almost an order of magnitude ... not bad for a couple of days of work. Nice going.

**Comment by matthewholman** [comment]
Rob is looking into reordering the sb441-n16 file so that the coefficients for all the asteroids are grouped by time.  That should speed things up on each first iteration, before the asteroid positions are cached.  JPL's code uses such custom files.

**Comment by hannorein** [comment]
That makes a lot of sense. We need to think about how to present that to the user as they no longer can use the standard files.

**Comment by matthewholman** [comment]
That's a good point.  Perhaps we could make the code work easily with either the standard or the custom file.  We could offer the custom file on the github site (assuming it's not too large) for those who really want the speed.

**Comment by hannorein** [comment]
That would be nice.

**Pull request merged**
