### PR TITLE
Adding/cleaning up examples

### PR DESCRIPTION
**Pull request by hannorein**
I'm removing all the old examples that don't work anymore with the current version of ASSIST. They are clearly valuable but they would really confuse people. We can always go back in the repository and fish them out if we need them (you can also make a copy of those files locally). 

I'm also adding a few more examples. I've added one with just ephemeris queries (no integration) and one which demonstrates the interpolation feature.

### CODE REVIEW

**Comment by aryaakmal** [comment]
Presumably this refers to the problem.c files under examples. I think we will update the jupyter notebook examples that correspond to the figures in the paper and include them in the documentation as with the rebound/reboundx documentaton.

**Comment by matthewholman** [comment]
I agree with that @hannorein .  I've kept a local copy.

**Comment by hannorein** [comment]
@aryaakmal I'm updating the jupyter notebook 3666_Holman.ipynb right now. If anyone else is working on something let me know so we don't interfere.

**Comment by aryaakmal** [comment]
@hannorein - you are much faster than I. So, please do go ahead. I had only
just begun working on 3666_Holman, so no worries there. Thank you for
letting us know you are on it.

**Pull request merged**
