### PR TITLE
Cache

### PR DESCRIPTION
**Pull request by hannorein**
We talked a bit about caches. I'm thinking about how to best implement that, focusing on the memory and how this looks like form the user perspective for now.

In contrast to `assist_ephem`, any cache is no longer read only. So every process needs their own cache if they want to operate in parallel. For that reason it might make sense to have a separate `assist_ephem_cache` structure that handles all the caching. I'm trying this out in this draft here. I've reimplemented the caching of the sun's position that was already happening in `assist_all_ephem` using static variables. We'd need to change that at some point anyway because it's not thread safe. 

The way it's implemented right now is that `assist_extras` automatically creates the new `assist_ephem_cache` structure. So the user doesn't need to do anything except if they want to use the function `assist_all_ephem` directly and still get the benefits of caching. If caching is not important, the pointer to `assist_ephem_cache` can just be null and everything is calculated on the fly.

Happy to think about other ways of doing this if anyone has an idea...

### CODE REVIEW

**Comment by aryaakmal** [comment]
Wow - very impressive.

**Comment by matthewholman** [comment]
That is very promising!  Nice, clean solution.  A 5x speed up puts ASSIST within a factor of 2-3 of the JPL small bodies code.

Although the current solution is more versatile, we could construct a similar one that caches the states of all the planets and asteroids together for a given time.  The cache would be first in time order then in body order, rather than body order first and then time order.  That might give a little speed up but probably not much.

**Comment by hannorein** [comment]
That's a good idea. Definitely worth trying out. 

I've tried a few things already, but so far almost everything has made it worse. Oh well, I guess that was only one really low hanging fruit. But I'm very keen to get the another factor of 2-3 out!

**Comment by hannorein** [comment]
Actually...

The 5x speedup was on my linux box. Running the benchmark on my laptop (Apple M1), I get consistently a speedup of 12x (!!). This is comparing my hannorein/cache branch to matthewholman/main. If one of you has a chance to run the benchmark, I'd be curious to see what kind of speedup you get.

**Comment by matthewholman** [comment]
That's awesome!  I added a benchmark file for my (old) MacBook.  But I haven't merged your latest code.  Would you like me to?

**Comment by hannorein** [comment]
I think it's safe to merge. But you can also easily check out my branch to run the benchmark without merging:

```
git remote add hannorein https://github.com/hannorein/assist.git
git fetch hannorein
git checkout hannorein/cache
```

**Comment by aryaakmal** [comment]
Awesome.

**Comment by matthewholman** [comment]
Thanks.  That gave me a 5.8x speed up on my old mac laptop.  Not bad!  Your M1 has something magic about it.

**Comment by aryaakmal** [comment]
I get about a 6.5x speed up on my SAO mac laptop. Not quite Hanno-level,
but pretty good.

**Comment by hannorein** [comment]
Thanks! That is very helpful. I suspected that the M1 is doing something special (the laptop is great and very fast - but I don't trust it for the speed comparisons).

It looks like most of the remaining time is now spend in the GR routine. But I am very hesitant to touch it. It's so complicated!  

There are various terms like these:
```c
const double dterm5dx = -3.0/C2*rijdotvj/_rij*((vxj-vxo)/_rij - rijdotvj*dxij/(_rij*_rij*_rij));
const double dterm5dy = -3.0/C2*rijdotvj/_rij*((vyj-vyo)/_rij - rijdotvj*dyij/(_rij*_rij*_rij));
const double dterm5dz = -3.0/C2*rijdotvj/_rij*((vzj-vzo)/_rij - rijdotvj*dzij/(_rij*_rij*_rij));
```
which might be optimized by doing something like 
```c
const double prefac1 = 1./_rij;
const double prefac1a = prefac1*rijdotvj;
const double prefac2 = -3.0/C2*prefac1a;
const double prefac3 = prefac1a*prefac1*prefac1;
const double dterm5dx = prefac2*((vxj-vxo)*prefac1 - dxij*prefac3);
const double dterm5dy = prefac2*((vyj-vyo)*prefac1 - dyij*prefac3);
const double dterm5dz = prefac2*((vzj-vzo)*prefac1 - dzij*prefac3);
```
These are the same mathematically but require fewer floating point operations. The compiler will not do this by itself because the order of operation is changed, resulting in slightly different floating point numbers. Do you have a sense for whether that's important or not? I suspect not, given that GR is always small compared to other contributions to the acceleration, so the final digits will probably always get cut off anyway. But again, I'm hesitant to touch anything given the complexity and the amount of work you've put in testing them term by term.

**Comment by matthewholman** [comment]
I am happy to take that kind of suggestion and compare the results to both previous ASSSIT results and to those from the JPL code.

**Comment by hannorein** [comment]
Great! The main ideas are:
- Break up long calculations into small parts. Reuse as many of the small parts as often as possible. 
- As it's already done nicely in the code: make variables constants whenever possible. Not reusing/reassigning variables might help the compiler to optimize things.
- Try to avoid using variables defined outside the function itself. For example, it might help caching `particles[i].x` in the function locally: `const double px = particles[i].x;`. That's because the CPU might not be able to predict if `particles[i]` has changed since it was last accessed. Then it has to invalidate a cache, leading to a slow memory lookup.
- Divisions are more expensive than multiplications. (hence try to calculate 1/r only once, then just multiply).
- Whenever you change something, run a benchmark. My changes often make things slower. Probably because I don't understand some fancy optimization the compiler or CPU is doing under the hood. You only want to keep changes that lead to a speedup.

**Comment by aryaakmal** [comment]
The variational terms for GR & harmonics are rather more complicated and I
imagine they use more resources. I don't believe any of the unit tests use
variational particles. Would it be worth adding a unit test or a
benchmark to address that?

**Comment by hannorein** [comment]
Yes definitely! Do I understand it correctly that the GR routine calculates quantities which are only used for variational particles even if none are present? If so that might be another low hanging fruit. 

In my benchmarks the harmonics force routines do not contribute a lot to the overall runtime. After GR, the next most time consuming function is the one for the direct terms.

**Comment by matthewholman** [comment]
Yes, that is correct (somewhat embarrassingly).  Essentially all the matrix components are calculated before the matrix is multiplied by the variational particle vectors.  We can easily put in a return if there are no variational particles.

**Comment by matthewholman** [comment]
I did check in which I simply removed all the calculations related to variational particles in the eih_GR function.  My benchmarks are:
1.36 s (no cacheing, GR variational calculations)
0.23 s (cacheing, GR variational calculations)
0.18 s (cacheing, no GR variational calculations)

**Pull request merged**
