### PR TITLE
Add benchmark results on an ARM core M1 Max Macbook

### PR DESCRIPTION
**Pull request by spenczar**
This is an Apple MacBookPro18,2. It has a 10-core M1 Max chip with 32GB of memory. rebound and assist were compiled with clang-1400.0.29.202 for arm64-apple-darwin21.6.0.

The results are _frighteningly fast_. I think it's safe to say that this code works well on ARM!

### CODE REVIEW

**Comment by hannorein** [comment]
Thanks! FWIW, we've tested it on ARM, but did most of the optimizations for i386 because we thought that might be most relevant for "production use". In fact, I undid some optimizations because they were faster on ARM, but slower on i386. A lot has to do with cache efficiency, which is hard to predict. Just reordering some instructions can have a significant effect.

**Comment by spenczar** [comment]
Right! I did not expect it to outperform the other recorded benchmarks so dramatically, that was a pleasant surprise.

I am happy to continue updating these benchmarks as new versions are released, or I can close this PR and let this PR itself be a snapshot of historical performance.

Or, a more realistic environment could be on a variety of Google Cloud instance classes, which I could do if you like.

**Comment by hannorein** [comment]
The benchmarks that've added so far run on stand-alone desktop machines. I don't think laptop or cloud based benchmarks are super useful in the long run. We'll never know what has changed on the hardware or software side if we run it in a virtual machine, if some other user is using the same physical CPU. For example, some cloud providers disable certain CPU features (AVX). It's all pretty random. And on a laptop/desktop it will depend on what other processes are running, temperature, battery status etc.

**Comment by hannorein** [comment]
Cool. I'd say just test it on whichever machine you plan on using it. Once you've found what seems to be a good optimization, send us a pull request and we'll run it on the machines we've been using before.

**Comment by hannorein** [comment]
(Ideally, we'd setup our own GitHub Actions runners on dedicated machines to always provide a benchmark with every push - but it's just overkill for this sort of small project)

**Comment by spenczar** [comment]
That sounds great to me. I'll close this.

**Pull request closed without merging**
